### ISSUE TITLE
Bug: "the ClickLine" attribute/function should return the " of <short name of target>"

### ISSUE THREAD

**Issue by ooper-zz** [defano/wyldcard#106]
Currently, "the clickline" returns only the line number of the field's clicked row, not the full parent, in the form of "line 1 of <card | background> field <part number>". 

This bug can be found in the "Audio Help" stack. 
It can be duplicated by writing a simple mouseUp script on a locked text field:
on mouseUp
   answer the clickLine --should answer "line x of card field x"
end mouseUp

**Comment by ooper-zz** [comment]
I will be working on this fix and send a PR when I am done.

**Comment by ooper-zz** [comment]
Quick update. I got this functionality working. I will finish the test and the PR Friday (tomorrow for me).

**Comment by ooper-zz** [comment]
I submitted a Pull Request

**Comment by ooper-zz** [comment]
Sorry, it's probably me learning Github, but I can't find your review comments for the pull request on pull #113. I am looking at the Conversation tab for it and see 0 🧐

Sent from my iPhone

On May 31, 2022, at 7:41 PM, Matt DeFano ***@***.***> wrote:

﻿

Thanks, @ooper-zz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fooper-zz&data=05%7C01%7C%7C0c1a7a5d50af41508f5e08da4378389f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896480871770154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TSplip8Jy9%2FnUtukqlIYlbqfvI5lWFw9oWASkjWFSjM%3D&reserved=0> . I left you a review comment—I think the implementation for the clickLine can be simplified. Take a look and let me know if you disagree.

**Comment by ooper-zz** [comment]
Hey @defano, I'm sorry, I can't find the PR review comment and what the simplification should be :( If you could add a link to this thread, It would be great and highly appreciated. Thanks! 

At any rate, I am on vacation and will be until the latter part of week of June 13.

**Comment by ooper-zz** [comment]
Thanks @defano, we did! 

I submitted the changes you suggested. Best approach, for sure. 
Take care.

**Comment by defano** [comment]
Awesome—thanks, @ooper-zz. I have merged your changes.
