### ISSUE TITLE
"Show all cards" menu command (UI)?

### ISSUE THREAD

**Issue by Jimw338** [defano/wyldcard#65]
Was there a "show all cards" menu item that small images of all the cards in the stack and let you select one that isn't in WyldCard, or am I mis-remembering from 25 years ago?

**Comment by defano** [comment]
I believe you're remembering the "Recent" command from the "Go" menu. That will display a window of card thumbnails.

This exists in WyldCard, but needs some work--it's behavior isn't consistent with HyperCard's.
