### ISSUE TITLE
"Statements" v. "Commands" - "addCmdStmnt" v. "answerDefaultCmd" ("stmnt" v. "cmd")?

### ISSUE THREAD

**Issue by Jimw338** [defano/wyldcard#71]
Is there a difference between "stmnt" and "cmd" for the labels after the "#" in the grammar?  I see that "add" command is "addCmdStmnt", while the "answer" command family is "answer..Cmd".  (And a few are "CmdStmnt")  Does the name (the ending at least) itself make a difference to the ANTLR parser generation, or is it just an arbitrary label.  Could I call a function (that returns something) a command (which doesn't) if I really wanted to?

**Comment by defano** [comment]
They're arbitrary. I'm not aware of any impact they have on the way Antlr generates the parser. You could call a function a command or just about anything else.

These inconsistencies are simply an artifact of a lack of good discipline on my part. ;)
