### ISSUE TITLE
Build with 'generateBundle' throws exception

### ISSUE THREAD

**Issue by swiftech** [defano/wyldcard#82]
What I ran:
`./gradlew generateBundle`

Result:
```

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

**Comment by defano** [comment]
Hi @swiftech , can you tell me which version of Java you're using and which OS you're seeing this on?

**Comment by swiftech** [comment]
@defano 

oracle jdk-17.0.1

macOS Catalina version 10.15.7

**Comment by defano** [comment]
Hi @swiftech , unfortunately WyldCard only supports Java 8 at this time. There are quite a few changes required to support Java 17 (mostly related to Google Guice) which I have not had time to implement.

You can run the program by using an older version of Java. I recommend utilizing [SDKMan](https://sdkman.io), then:

```
$ sdk install java 8.0.292.hs-adpt
$ sdk use java 8.0.292.hs-adpt
$ gradlew clean
$ gradlew run
```
