### ISSUE TITLE
Wikipedia entry

### ISSUE THREAD

**Issue by rozek** [defano/wyldcard#89]
Good morning!

I think, WyldCard would definitely be worth an entry in Wikipedia! I've just mentioned it in the german article for HyperCard, refering to the related Wiki.

But I would also like to add a separate article about WyldCard.

Do you allow me to translate texts from your WyldCard wiki in order to be placed on that page? Many of your sentences could not be written better (e.g., more concise) and, thus, I would like to avoid having to think about phrases of similar quality...

**Comment by defano** [comment]
Sure—by all means. I'd be honored!

**Comment by rozek** [comment]
Thank you very much - I'll create the entry over the weekend (have to prepare tomorrow's lectures right now)

**Comment by rozek** [comment]
Well, I've just created a very first entry for WyldCard in the german Wikipedia (the URL is [https://de.wikipedia.org/wiki/WyldCard](https://de.wikipedia.org/wiki/WyldCard) but you may not be able to see it until it has been validated by Wikipedia staff).

Am I allowed to upload the image shown in the WyldCard repository README? According to my understanding, I will have to upload to "Wikipedia Commons" in order to be able to reference it

**Comment by rozek** [comment]
Well, Wikipedia wants me to provide some references proving that Wyldcard has some spread and is in use by some users - do you have such references? Google did not reveal anything...

**Comment by defano** [comment]
Sadly, no—the only thing I can suggest is the number of stars or forks of the repository. 

As an alternative (if they reject the article outright), I was thinking of adding WyldCard as a reference or link from the main HyperCard article, which, at least in the English version, enumerates some open source and commercial alternatives.

**Comment by rozek** [comment]
Well, mentioning WyldCard (in the German Wikipedia) is what I did first - and that will remain
