### ISSUE TITLE
Visual Background mode indicator missing

### ISSUE THREAD

**Issue by ooper-zz** [defano/wyldcard#92]
Given a user is in card mode
When an Edit/Background menu item is chosen
Then the stack background should display a visual indication of being in the background mode. The orig. HC had a patterned outline of the menubar. 

 Conversely,
Given a user is in background mode
When an Edit/Background menu item is chosen
Then the stack background should hide the visual background mode indicator as described above

**Comment by defano** [comment]
Hi @ooper-zz ,

Agreed—

HyperCard solved this problem by adding a decoration to the menu bar. Unfortunately, Swing does not provide this capability (as far as I've been able to tell). As an inexpensive workaround, I add the string `(Background)` to the card window's name to denote the user is editing the background.

Any suggestions of how to denote background editing, short of adding the patterned indicator to the menu bar?

**Comment by ooper-zz** [comment]
I think one would probably have to drop down to the awt peer classes in all platforms to do this, which is impractical for this purpose.  I think a pattern around the window title should give us the desired effect for now and will work the same cross-platform, like yay:
![bkgd-indicator-hack](https://user-images.githubusercontent.com/3395566/167274260-9668a3da-72c4-4120-bc08-427c26bad1b7.jpg)
 
If you are ok, I'll submit a pull request later on and move on to bigger things.

**Comment by ooper-zz** [comment]
I went ahead and submitted a Pull Request for your review. Thanks

**Comment by defano** [comment]
Accepted and merged; closing.
