### ISSUE TITLE
The number of the current background doesn't resolve

### ISSUE THREAD

**Issue by ooper-zz** [defano/wyldcard#94]
When I send "the number of this bg" via the message box, the system returns an error. It should return the number for the current background with respect to the stack. None of the other legal synonyms for 'background' seem to work either.

**Comment by defano** [comment]
Nice catch! Turned out to be a dumb mistake in the expression used to find the `number` property of a background. It should be resolved now.

**Comment by ooper-zz** [comment]
Awesome. Thanks for taking care of it so quickly. That fix will give me a good entry point into wh look at in a similar situation moving forward.  Thinking about importing some of the most well-known stacks. Perhaps we can surprise Danny Goodman with Focal Point running on WyldCard, haha. I am sure that one will uncover plenty of stuff to work on. TTYL

Sent from my iPhone

On May 15, 2022, at 6:38 AM, Matt DeFano ***@***.***> wrote:

﻿

Nice catch! Turned out to be a dumb mistake in the expression used to find the number property of a background. It should be resolved now.
