### ISSUE TITLE
"The version" does not resolve

### ISSUE THREAD

**Issue by ooper-zz** [defano/wyldcard#96]
When importing stacks that use the version property (e.g. FocalPoint II) do not resolve. I realize that old stacks are referring to HyperCard, but perhaps we can assume that any stack that is importable (HC 2.x) should return our baseline version (2.4 as documented).  At this point, that function doesn't even return WyldCard's version.

**Comment by defano** [comment]
Agreed. Adding a new zero-arg function `the version` that just returns `new Value("2.4.1");` should be pretty easy. Wanna submit a PR for that? Otherwise I can get it in sometime this week.

**Comment by ooper-zz** [comment]
Thanks for taking a look. I'll add a PR for that. It's a perfect one to take on, so that I get more intimate with the software. If you can give me some pointers, it would be even better.

Mark, I can be reached at ***@***.*** I think it would be awesome to have a quick chat about the future of wyldCard. If you send me an email there, I can give you my phone #, so it doesn't end up here in the wild.

Looking forward,
Carl
________________________________

**Comment by ooper-zz** [comment]
I figured it out following another no-arg function. Easy enough, but I broke some tests and will follow up tomorrow. TTYL

**Comment by defano** [comment]
I don't think Github wants you sharing your email address :) It's been redacted. 

Nevertheless, it's probably easier for me to respond in this forum, anyway, plus it's then visible for others who might want to contribute or have the same questions, too.

If you like, open a new issue like "Future of WyldCard" or "Questions about design" and we can go back-and-forth in writing.

**Comment by ooper-zz** [comment]
I noticed the redaction --for the better, no doubt. Great points!  I added an issue "Discussions:Future of WyldCard" and will add some questions and basic assertions. I guess we can set the forum towards a FAQ and Road Map section from there...

**Comment by ooper-zz** [comment]
Hey, I have submitted comments for my fixes and have them checked in on my Forked master branch, but please let me know how to proceed with the new pull request, as I am not a regular GitHub user.  Thanks!

**Comment by defano** [comment]
Your recent change looks good. Simply updating the branch that is open for review implicitly updates the PR, too. I have merged. Thanks for that change!
